### ISSUE TITLE
cannot load such file: htmltoword

### ISSUE THREAD

**Issue by nealmcb** [pfaffman/discourse-downloader#1]
There seems to be a dependency that I don't have, on Ubuntu Bionic 18.04 LTS:

``` ruby
$ ruby ./discourse-downloader
Traceback (most recent call last):
  2: from ./discourse-downloader:6:in `<main>'
  1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require' 
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- htmltoword (LoadError)
```
I don't remember / know much about Ruby, but would prefer to not have to modify any system-level files, e.g. via a `sudo gem install`

**Comment by pfaffman** [comment]
I understand your frustration, but ruby without gems is a bit like . . . uh, a car without an engine? There really isn't a feasible alternative, I'm afraid.

**Comment by nealmcb** [comment]
Thanks for the quick response!

Since I saw this in the README:

> Requires no external GEMS

and I didn't see any references to `htmltoword` outside the `require` statement, I was really hoping I could just comment it out as an obsolete reference of some sort.

And re gem installation, I was hoping there was something like Python's `--user` or `venv` approaches to install gems in a local environment, or a standard packaging of the gem in question (for `apt-get`).

At any rate, I played around a bit more, and it does seem to work with that line commented out, and no extra gems:

    ./discourse-downloader https://forum.electionscience.org/t/cess-new-anti-star-hit-piece/654

But for future reference, this doesn't work:

    $ ./discourse-downloader -c /dev/null https://forum.electionscience.org/t/cess-new-anti-star-hit-piece/653
    ./discourse-downloader:208:in `load': cannot load such file -- ~/src/discourse-downloader/apikeys (LoadError)

unless I do create the `~/src/discourse-downloader/apikeys` file.

**Comment by pfaffman** [comment]
Oh. Yeah. Sorry. That's a lie. I'll try to have a look next week.

**Comment by pfaffman** [comment]
I made a new commit that removes the `htmltoword` dependency and doesn't try to load the `apikey` file if it doesn't exist.

**Comment by nealmcb** [comment]
For the record, the commit was 93cfb691f
It resolves this issue.

Now all you need to do is 

    ./discourse-downloader https://forum.electionscience.org/t/cess-new-anti-star-hit-piece/653

Thanks!
